import {
  FaRegGem,
  FaApple,
  FaAndroid,
  FaChevronCircleUp,
  FaCheckCircle,
  FaBolt,
  FaUserSecret,
  FaMoneyCheckAlt,
  FaFilter,
  FaCcVisa,
  FaPowerOff,
  FaPhoneAlt,
  FaEnvelope,
  FaMapMarkerAlt,
  FaSkype,
  FaFacebook,
  FaTwitter,
  FaInstagram,
} from "react-icons/fa";
import { BsAndroid2 } from "react-icons/bs";
import { RxHamburgerMenu } from "react-icons/rx";
import { GrClose } from "react-icons/gr";

export {
  GrClose as Close,
  RxHamburgerMenu as Hamburger,
  FaRegGem as Gem,
  FaApple as Apple,
  FaAndroid as Android,
  FaChevronCircleUp as Chevron,
  FaCheckCircle as Check,
  FaBolt as Bolt,
  FaUserSecret as User,
  FaMoneyCheckAlt as Money,
  FaFilter as Filter,
  FaCcVisa as Visa,
  FaPowerOff as PowerOff,
  FaPhoneAlt as Phone,
  FaEnvelope as Envelope,
  FaMapMarkerAlt as Marker,
  FaSkype as Skype,
  FaFacebook as Facebook,
  FaTwitter as Twitter,
  FaInstagram as Instagram,
  BsAndroid2 as AndriodIco,
};
